version: '2.1'
services:
  db:
    image: postgres:9.1
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  odoo:
    image: odoo:8
    container_name: odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - ./addons:/mnt/extra-addons/
      - ./odoo_data:/var/lib/odoo/
#      - ./openerp:/usr/lib/python2.7/dist-packages/openerp/
